# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

end = 4000000

n2 = 1
n1 = 2
n = 0
answer = 2

while (n < end):
    n = n2 + n1

    # print ("n: ", n)
    if (n % 2 == 0 and n < end):
        answer += n
        print ("answer: ", answer)

    n2 = n1
    n1 = n

print("answer: ", answer)
